version: "3.1"
services:
  db:
    image: mysql:latest
    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: core

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app           # Where the Dockerfile is stored
    restart: always

    volumes:
      - ./app:/app

    links:
      - db

    ports:
      - "5000:5000"